name: Matematika G1
code: BMETE94BG01
lecturer: Dr. Szilágyi Brigitta
breakdown:
  credits: 6
  lectures: 4
  practicals: 2
  labs: 0
  is_exam: true
book:
  dir: book
  source: main.tex
  target: G1-tankonyv
  display_name: G1 előadás jegyzet
online_notes: null
practice_material:
  dir: practice
  solutionsDir: practice-solutions
  files:
    - source: 01.tex
      target: G1-gyak-01
      solution: G1-gyak-01-megoldas.pdf
      video_link: https://youtu.be/xIiAnpM3uSI
      video_mistakes:
        - '44:10 -> Ha két vektor skaláris szorzata 0, ÉS EGYIK VEKTOR SEM
          NULLVEKTOR, akkor a két vektor merőleges egymásra.'
        - '1:14:59 -> Elszámolás: AC vektor és AB vektor vektoriális szorzatának
          első koordinátája -6 (nem -14), illetve a harmadik koordináta 12 (nem
          -20)! Így a vektoriális szorzat abszolút értéke:
          gyök((-6)^2+(-18)^2+(12)^2)=6*gyök(14). Innen az ABC háromszög
          területe: 3*gyök(14)=11,22. (7. feladat)'
        - '1:19:08 -> Lemaradt a 3. élvektor hosszúságának figyelembevétele. Ha
          kiemelünk 7-et, akkor (2; 3; 6), illetve (-2; -3; -6) vektorokat
          kapjuk, amik már egyenlő hosszúságúak a feladat szövegében megadott 2
          élvektorral. (8. feladat)'
        - '1:21:04 -> uvw=wuv=-uwv=-wvu, azaz előjelet akkor vált, ha
          felcseréljük nem ciklikusan a vektorok sorrendjét. (Hiszen a vegyes
          szorzatban szereplő vektoriális szorzat antikommutatív.)'
        - '1:21:50 -> koMplanáris'
      display_name: G1 1. gyakorlat
      description: Analitikus geometria I – Vektorok
      week: 1
    - source: 02.tex
      target: G1-gyak-02
      solution: G1-gyak-02-megoldas.pdf
      video_link: https://youtu.be/qOatMC5SSCU
      video_mistakes:
        - '32:43 - irányvektorok és nem egységvektorok'
      display_name: G1 2. gyakorlat
      description: Analitikus geometria II – Térgeometriai alakzatok
      week: 2
    - source: 03.tex
      target: G1-gyak-03
      solution: G1-gyak-03-megoldas.pdf
      video_link: https://youtu.be/R7WRV5dkUVQ
      video_mistakes:
        - '1:20:48-nál egy elírás látható: nem parabola hanem ELLIPSZIS
          egyenlete (jelen számok esetében pedig pont kör), a parabola egyeblete
          a c) részben volt látható!'
      display_name: G1 3. gyakorlat
      description: Komplex számok
      week: 3
    - source: 04.tex
      target: G1-gyak-04
      display_name: G1 4. gyakorlat
      solution: G1-gyak-04-megoldas.pdf
      video_link: https://youtu.be/Q7re319JuNo5
      description: Numerikus sorozatok I
      week: 4
    - source: 05.tex
      target: G1-gyak-05
      solution: G1-gyak-05-megoldas.pdf
      video_link: https://youtu.be/2EL1Qg0bEnU
      video_mistakes:
        - '27:00 → Mivel n tart a végtelenbe, így a számláló negatív lesz
          n=2-től. De (!) n=1 esetén pont nulla, azaz a_1=a_2. A második tagtól
          kezdve pedig már szigorúan monoton csökken, ahogy a videóban is
          elhangzik. Felső korlátnak pedig K=a_1=a_2=3 választható.'
        - '34:55 → A rekurzív sorozatok bevezetésénél használt általános képlet
          pontatlan. A táblán az szerepel, hogy az a_n=f(a_n-1), ami nem
          teljesen pontos. Hiszen rekurzív sorozatok esetén a sorozat általános
          (a_n) tagját a korábbi tagok segítségével határozzuk meg, nem
          feltétlen csak az eggyel korábbi (a_n-1) taggal.'
      display_name: G1 5. gyakorlat
      description: Numerikus sorozatok II
      week: 5
    - source: 06.tex
      target: G1-gyak-06
      display_name: G1 6. gyakorlat
      solution: G1-gyak-06-megoldas.pdf
      video_link: https://youtu.be/VJoVvFfEagc
      video_mistakes:
        - '58:36 -> A konstans megfogalmazás a számlálóra nem megfelelő. A
          sin(u) mindig korlátos. Az F4-es feladatban az utolsó lépésnél,
          lemaradt a cos(5x). Helyesen a kifejezés: lim x->0
          sin(8x)/sin(5x)*8x*5x/(8x*5x)*cos(5x). Alkalmazzuk a sin(x)/x -es
          azonosságot és tudjuk hogy cos(5x) ->1 ha x->0, így adódik az
          eredmény, ami 8/5'
      description: Függvények – folytonosság, határérték
      week: 6
    - source: 07.tex
      target: G1-gyak-07
      display_name: G1 7. gyakorlat
      solution: G1-gyak-07-megoldas.pdf
      video_link: https://youtu.be/qzTEZYRykUA
      description: Differenciálszámítás I
      week: 7
    - source: 08.tex
      target: G1-gyak-08
      display_name: G1 8. gyakorlat
      solution: G1-gyak-08-megoldas.pdf
      description: Differenciálszámítás II
      video_link: https://youtu.be/t_ZtR2x0eFA
      week: 8
    - source: 09.tex
      target: G1-gyak-09
      display_name: G1 9. gyakorlat
      solution: G1-gyak-09-megoldas.pdf
      description: Differenciálszámítás III
      video_link: https://youtu.be/wImfxPqRqNk
      week: 9
    - source: 10.tex
      target: G1-gyak-10
      display_name: G1 10. gyakorlat
      solution: G1-gyak-10-megoldas.pdf
      description: Integrálszámítás I
      video_link: https://youtu.be/2YKb0qVEljo
      week: 10
    - source: 11.tex
      target: G1-gyak-11
      display_name: G1 11. gyakorlat
      description: Integrálszámítás II
      video_link: https://youtu.be/7Wc1erfk1Ug
      video_mistakes:
        - '17:55 -> F5-ös példánál lemaradt a +c valós konstans.'
      week: 11
    - source: 12.tex
      target: G1-gyak-12
      display_name: G1 12. gyakorlat
      solution: G1-gyak-12-megoldas.pdf
      description: Integrálszámítás III
      video_link: https://youtu.be/mU497mbNvyg
      video_mistakes:
        - 'F3: 12:57-nél a nevezőben a 3 helyett 2 a helyes kifejezés.'
        - 'F4: Helyettesítéses integrálról van szó, vissza kell helyettesíteni
          és az eredményt x függvényében kell megadni. A végleges eredmény:
          -2sqrt(x)cos(sqrt(x))+2sin(sqrt(x))+C.'
        - 'F5: Szintén vissza kell helyettesíteni, így a végleges eredmény:
          ln(ln(x))*ln(x)-ln(x)+C F8: visszahelyettesítve:
          1/2*((2x-1)^(7/2)/14-2/3*(2x-1)^(5/2)+1/2*(2x-1)^(3/2))+C.'
        - 'F10: Az integrálás kiértékelésnél a chx behelyettesítésénél hibás az
          előjel, ugyanakkor a megoldás helyes.'
      week: 12
    - source: 13.tex
      target: G1-gyak-13
      display_name: G1 11. gyakorlat
      description: Integrálszámítás IV
      video_link: https://youtu.be/bzMjsAGt1x0
      week: 13
    - source: 14.tex
      target: G1-gyak-14
      display_name: G1 14. gyakorlat
      description: Numerikus sorok
      video_link: https://youtu.be/Y33dpnUZ5hk
      week: 14
hide_lectures: true
lectures:
  - room: CHFMAX
    day: 2 # Tuesday
    start: [8, 15]
    end: [10, 0]
  - room: CHFMAX
    day: 5 # Friday
    start: [10, 15]
    end: [12, 0]
hide_practicals: true
practicals:
  - group: HM1
    room: R501
    day: 1 # Monday
    start: [8, 15]
    end: [10, 0]
    edubase: https://www.edubase.net/coupon/6xXc9n9mdn8DfL46
    staff:
      - name: Beharóczki István
      - name: Sovák Adrienn
  - group: 'HM2'
    room: 'R513'
    day: 1 # Monday
    start: [10, 15]
    end: [12, 0]
    edubase: 'https://www.edubase.net/coupon/ejWTL7MpQzkiG4nW'
    staff:
      - name: 'Biebel Botond'
      - name: 'Pesti Patrik'
  - group: 'HM3'
    room: 'R513'
    day: 1 # Monday
    start: [16, 15]
    end: [18, 0]
    edubase: 'https://www.edubase.net/coupon/WK39KrnBS96bYa4C'
    staff:
      - name: 'Biebel Botond'
      - name: 'Pesti Patrik'
  - group: 'HM4'
    room: 'R513'
    day: 2 # Tuesday
    start: [14, 15]
    end: [16, 0]
    edubase: 'https://www.edubase.net/coupon/AbOwIp5tXQ8LYJ5q'
    staff:
      - name: 'Török Regina'
      - name: 'Tusor Bálint'
  - group: 'HM5'
    room: 'R515'
    day: 3
    start: [12, 15]
    end: [14, 0]
    edubase: 'https://www.edubase.net/coupon/Ox9fS9dsw9thHT1A'
    staff:
      - name: 'Sándor Tibor'
  - group: 'HM6'
    room: 'R516'
    day: 3 # Wednesday
    start: [14, 15]
    end: [16, 0]
    edubase: 'https://www.edubase.net/coupon/8SCh2JFsyU7XrxFY'
    staff:
      - name: 'Kun László Ákos'
  - group: 'HM7'
    room: 'R501'
    day: 4 # Thursday
    start: [10, 15]
    end: [12, 0]
    edubase: 'https://www.edubase.net/coupon/76SkYrSQRQ4O91hF'
    staff:
      - name: 'Patacsi Mátyás'
  - group: 'HE1'
    room: 'R513'
    day: 4
    start: [12, 15]
    end: [14, 0]
    edubase: 'https://www.edubase.net/coupon/JGz2gogz7NsxZUpn'
    staff:
      - name: 'Sándor Tibor'
  - group: 'HE2'
    room: 'R514'
    day: 4 # Thursday
    start: [12, 15]
    end: [14, 0]
    edubase: 'https://www.edubase.net/coupon/TWUEMzRzK3V8LjRD'
    staff:
      - name: 'Prónai Sára'
