name: Matematika G3
code: BMETE94BG03
lecturer: Dr. Szilágyi Brigitta
breakdown:
  credits: 4
  lectures: 2
  practicals: 2
  labs: 0
  is_exam: false
book:
  dir: book
  source: main.tex
  target: G3-tankonyv
  display_name: G3 előadás jegyzet
online_notes: null
hide_edubase: true
practice_material:
  dir: practice
  latex_solutions_dir: practice-latex-solution
  files:
    - source: 01.tex
      target: G3-gyak-01
      latex_solution_source: 01.tex
      latex_solution_target: G3-gyak-01-megoldas
      display_name: G3 1. gyakorlat
      description: Vektoranalízis – Ismétlés, operátorok
      week: 1
    - source: 02.tex
      target: G3-gyak-02
      # latex_solution_source: 02.tex
      # latex_solution_target: G3-gyak-02-megoldas
      display_name: G3 2. gyakorlat
      description: Vektoranalízis – Operátorok, potenciálosság
      week: 2
    - source: 03.tex
      target: G3-gyak-03
      # latex_solution_source: 03.tex
      # latex_solution_target: G3-gyak-03-megoldas
      display_name: G3 3. gyakorlat
      description: Vektoranalízis – Görbék, görbementi integrál
      week: 3
    - source: 04.tex
      target: G3-gyak-04
      # latex_solution_source: 04.tex
      # latex_solution_target: G3-gyak-04-megoldas
      description: Vektoranalízis – Felületek, felületi integrál
      week: 4
    - description: Vektoranalízis – Térfogati integrál, szöveges feladatok
      week: 5
    - source: 06.tex
      target: G3-gyak-06
      display_name: G3 6. gyakorlat
      description: Vektoranalízis – Integrálátalakító tételek
      week: 6
    - description: Vektoranalízis – Gyakorlás
      week: 7
    - description: Differenciálegyenletek bevezetés
      week: 8
    - description: Elsőrendű és szétválasztható differenciálegyenletek
      week: 9
    - description:
        Elsőrendű lineáris és másodrendű hiányos differenciálegyenletek
      week: 10
    - description: Egzakt és speciális differenciálegyenletek
      week: 11
    - description: Állandó együtthatós differenciálegyenletek
      week: 12
    - description: Differenciálegyenlet-rendszerek I
      week: 13
    - description: Differenciálegyenlet-rendszerek II
      week: 14
hide_lectures: true
lectures:
  - room: CHFMAX
    day: 5 # Friday
    start: [8, 15]
    end: [10, 00]
hide_practicals: true
practicals:
  - group: H1
    room: R501
    day: 2 # Tuesday
    start: [16, 15]
    end: [18, 0]
    staff:
      - name: Kun László Ákos
  - group: H2
    room: R513
    day: 2 # Tuesday
    start: [16, 15]
    end: [18, 0]
    staff:
      - name: Sándor Tibor
  - group: H3
    room: R510
    day: 2 # Tuesday
    start: [16, 15]
    end: [18, 0]
    staff:
      - name: Kun Timon
      - name: Beharóczki István
  - group: H4
    room: R510
    day: 3 # Wednesday
    start: [8, 15]
    end: [10, 0]
    staff:
      - name: Tusor Bálint
  - group: H5
    room: R510
    day: 3 # Wednesday
    start: [10, 15]
    end: [12, 0]
    staff:
      - name: Kun László Ákos
  - group: H6
    room: R517
    day: 3 # Wednesday
    start: [14, 15]
    end: [16, 0]
    staff:
      - name: Kun László Ákos
  - group: H7
    room: R501
    day: 3 # Wednesday
    start: [16, 15]
    end: [18, 0]
    staff:
      - name: Sándor Tibor
  - group: H8
    room: R515
    day: 4 # Thursday
    start: [16, 15]
    end: [18, 0]
    staff:
      - name: Biebel Botond
      - name: Pesti Patrik
  - group: H9
    room: R501
    day: 1 # Monday
    start: [12, 15]
    end: [14, 0]
    staff:
      - name: Prónai Sára
  - group: H10
    room: R514
    day: 2 # Tuesday
    start: [8, 15]
    end: [10, 0]
    staff:
      - name: Hegyi Norbert
